from temp import *
s = scheduling_algo(3)
s.add_process(1,0,5)
s.add_process(2,2,3)
s.add_process(3,4,2)
s.FCFS()
s.RR(2)
s.FCFS_Arrival()
s.RR_waiting_time(2)
s.RR_turnRound_time(2)
s.FCFS_waiting_time()
s.FCFS_turnRound_time()
s.FCFS_A_waiting_time()
s.FCFS_A_turnRound_time()